---
title: "Linear models"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

## Model: Outcome = Charges

```{r}
mpv_df_charges =
  read_csv("./data/mpv_final.csv") %>% 
  mutate(
    charges = case_when(
      startsWith(criminal_charges, "Charged") ~ 1,
      startsWith(criminal_charges, "No") ~ 0),
    race_rec = case_when(
      race == "Unknown race" ~ "Unknown",
      race == "unknown race" ~ "Unknown",
      race == "Native American" ~ "Other",
      race == "Pacific Islander" ~ "Other",
      race == "Black" ~ "Black",
      race == "Hispanic" ~ "Hispanic",
      race == "White" ~ "White",
      race == "Asian" ~ "Asian"),
    race_rec = fct_infreq(race_rec),
    age_rec = 
      cut(age, breaks = c(0,20,40,60,100), right = FALSE),
    age_rec = fct_infreq(age_rec),
    MI = case_when(
      symptoms_of_mental_illness == "Yes" ~ "Yes",
      symptoms_of_mental_illness == "No" ~ "No",
      symptoms_of_mental_illness == "Unknown" ~ "Unknown",
      symptoms_of_mental_illness == "Drug or alcohol use" ~ "No"),
    gunshot = case_when(
      cause_of_death == "Asphyxiated" ~ "No",
      cause_of_death == "Pepper Spray, Physical Restraint" ~ "No",
      cause_of_death == "Beaten Chemical agent/Pepper spray" ~ "No",
      cause_of_death == "Gunshot" ~ "Yes",
      cause_of_death == "Gunshot, Bean Bag Gun" ~ "Yes",
      cause_of_death == "Gunshot, Beanbag Gun" ~ "Yes",
      cause_of_death == "Gunshot, Pepper Spray" ~ "Yes",
      cause_of_death == "Gunshot, Police Dog" ~ "Yes",
      cause_of_death == "Gunshot, Stabbed" ~ "Yes",
      cause_of_death == "Gunshot, Taser" ~ "Yes",
      cause_of_death == "Gunshot, Unspecified Less Lethal Weapon" ~ "Yes",
      cause_of_death == "Gunshot, Vehicle" ~ "Yes",
      cause_of_death == "Other" ~ "No",
      cause_of_death == "Pepper Spray" ~ "No",
    )) %>% 
  filter(MI != "Unknown", race_rec != "Unknown", gender != "Transgender", gender != "Unknown") %>% 
  select(MI, age_rec, race_rec, charges, gender, gunshot)

xtabs(~charges + MI, data = mpv_df_charges)
xtabs(~charges + gender, data = mpv_df_charges)
xtabs(~gunshot + MI, data = mpv_df_charges)
```

Modeling charges laid as outcome:

```{r}
fit = glm(charges ~ race_rec, data = mpv_df_charges, family = "binomial")

broom::tidy(fit) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "race_rec", "Race: ")
  ) %>% 
  knitr::kable(digits = 3)
```

```{r}
fit = glm(charges ~ age_rec, data = mpv_df_charges, family = "binomial")

broom::tidy(fit) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "age_rec", "Age: ")
  ) %>% 
  knitr::kable(digits = 3)
```

```{r}
fit = glm(charges ~ gender, data = mpv_df_charges, family = "binomial")

broom::tidy(fit) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "gender", "Gender: ")
  ) %>% 
  knitr::kable(digits = 3)
```

```{r}
fit = glm(charges ~ gunshot, data = mpv_df_charges, family = "binomial")

broom::tidy(fit) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "gunshot", "Gunshot: ")
  ) %>% 
  knitr::kable(digits = 3)
```

## Model 2: Outcome = MI


```{r}
mpv_df_mi =
  read_csv("./data/mpv_final.csv") %>% 
  mutate(
    charges = case_when(
      startsWith(criminal_charges, "Charged") ~ 1,
      startsWith(criminal_charges, "No") ~ 0),
    race_rec = case_when(
      race == "Unknown race" ~ "Unknown",
      race == "unknown race" ~ "Unknown",
      race == "Native American" ~ "Other",
      race == "Pacific Islander" ~ "Other",
      race == "Black" ~ "Black",
      race == "Hispanic" ~ "Hispanic",
      race == "White" ~ "White",
      race == "Asian" ~ "Asian"),
    race_rec = fct_infreq(race_rec),
    age_rec = 
      cut(age, breaks = c(0,20,40,60,100), right = FALSE),
    age_rec = fct_infreq(age_rec),
    MI = case_when(
      symptoms_of_mental_illness == "Yes" ~ 1,
      symptoms_of_mental_illness == "No" ~ 0,
      symptoms_of_mental_illness == "Drug or alcohol use" ~ 0),
    gunshot = case_when(
      cause_of_death == "Asphyxiated" ~ "No",
      cause_of_death == "Pepper Spray, Physical Restraint" ~ "No",
      cause_of_death == "Beaten Chemical agent/Pepper spray" ~ "No",
      cause_of_death == "Gunshot" ~ "Yes",
      cause_of_death == "Gunshot, Bean Bag Gun" ~ "Yes",
      cause_of_death == "Gunshot, Beanbag Gun" ~ "Yes",
      cause_of_death == "Gunshot, Pepper Spray" ~ "Yes",
      cause_of_death == "Gunshot, Police Dog" ~ "Yes",
      cause_of_death == "Gunshot, Stabbed" ~ "Yes",
      cause_of_death == "Gunshot, Taser" ~ "Yes",
      cause_of_death == "Gunshot, Unspecified Less Lethal Weapon" ~ "Yes",
      cause_of_death == "Gunshot, Vehicle" ~ "Yes",
      cause_of_death == "Other" ~ "No",
      cause_of_death == "Pepper Spray" ~ "No",
    )) %>% 
  filter(MI != "Unknown", race_rec != "Unknown", gender != "Transgender", gender != "Unknown") %>% 
  select(MI, age_rec, race_rec, charges, gender, gunshot)

xtabs(~MI + gender, data = mpv_df_charges)
```

Modeling charges laid as outcome:

```{r}
fit_mi_race = glm(MI ~ race_rec, data = mpv_df_mi, family = "binomial")

broom::tidy(fit_mi_race) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "race_rec", "Race: ")
  ) %>% 
  knitr::kable(digits = 3)
```

```{r}
fit_mi_gender = glm(MI ~ gender, data = mpv_df_mi, family = "binomial")

broom::tidy(fit_mi_gender) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "gender", "Gender: ")
  ) %>% 
  knitr::kable(digits = 3)
```

```{r}
fit_mi_age = glm(MI ~ age_rec, data = mpv_df_mi, family = "binomial")

broom::tidy(fit_mi_age) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "age_rec", "Age: ")
  ) %>% 
  knitr::kable(digits = 3)
```

## Hypothesis tests

Testing influence of mental illness symptoms. THIS DOESN'T WORK - unclear why, will revisit.

```{r}
fit_null = glm(MI ~ race_rec, data = mpv_df_mi, family = "binomial")
fit_alt = glm(MI ~ race_rec + gender, data = mpv_df_mi, family = "binomial")

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```
