---
title: "Maps for MPV"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(leaflet)
library(rvest)
library(shiny)

knitr::opts_chunk$set(
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Retrieving the MPV Tidy Dataset

```{r}
mpv_data =
  read_csv("./data/mpv_final.csv")
```


## Year Leaflet -- with city and police dept in the label

```{r, warning=FALSE}
pal <- colorNumeric(
  palette = "viridis",
  domain = mpv_data$year)


mpv_data %>% 
  drop_na() %>% 
  mutate(
    lab = str_c("City: ", city, "<br>Police Department: ", police_dept)) %>%
  leaflet() %>% 
  addTiles() %>% 
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addLegend("bottomright", pal = pal,
            values = ~year,
            title = "Year",
            labFormat = labelFormat(big.mark = ""),
            opacity = 1) %>% 
  addCircleMarkers(
    ~lng, ~lat,
    color = ~pal(year),
    radius = 0.5,
    popup = ~lab)
```


## Age Leaflet -- with symptoms of mental illness and whether officer was charged as label

```{r}
pal <- colorNumeric(
  palette = "viridis",
  domain = mpv_data$age)


mpv_data %>% 
  drop_na() %>% 
  mutate(
    lab = str_c("Age: ", age,
                "<br>Symptoms of Mental Illness: ", symptoms_of_mental_illness,
                "<br>Charges on the Police: ", criminal_charges)) %>%
  leaflet() %>% 
  addTiles() %>% 
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addLegend("bottomright", pal = pal,
            values = ~age,
            title = "Age",
            opacity = 1) %>% 
  addCircleMarkers(
    ~lng, ~lat,
    color = ~pal(age),
    radius = 0.5,
    popup = ~lab)
```


## USA data

```{r}

usa_protest = read_csv("./data/usa_tidy.csv")

pal <- colorNumeric(
  palette = "viridis",
  domain = usa_protest$fatalities)

usa_protest %>%
  mutate(
    lab = str_c("City: ", usa_protest$city, "<br>Type of Protest: ", usa_protest$event_type)) %>%
  leaflet() %>% 
  addTiles() %>% 
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addLegend("bottomright", pal = pal,
            values = usa_protest$fatalities,
            title = "Fatalities",
            labFormat = labelFormat(big.mark = ""),
            opacity = 1) %>% 
  addCircleMarkers(
    ~longitude, ~latitude,
    color = ~pal(usa_protest$fatalities),
    radius = 0.5,
    popup = ~lab)
 
```

