---
title: "Plotting for All Datasets"
output: github_document
editor_options: 
  chunk_output_type: console
---

## MPV Dataset

The plot below visualizes the total number of people killed by police, arranged by police department.

```{r}
police_dept_plot = 
  mpv_df %>% 
  count(police_dept) %>% 
  rename(total_killed = n) %>% 
  filter(total_killed >= 49) %>% 
  mutate(
    police_dept = factor(police_dept),
    police_dept = fct_reorder(police_dept, total_killed)
  ) %>% 
  ggplot(aes(x = police_dept, y = total_killed)) + 
  geom_point()
  
  
  ggplot(aes(x = police_dept, y = total_killed, fill = police_dept)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r}
police_dept_plot = 
  mpv_df %>% 
  group_by(state) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  rename(total_killed = n) %>% 
  filter(total_killed >= 49) %>% 
  ggplot(aes(x = police_dept, y = total_killed, fill = police_dept)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


