---
title: "Project Report"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
library(readr)
library(readxl)
library(patchwork)
library(leaflet)
library(rvest)
#you'll need to install the packages below in order to run animated plots or knit
library(gganimate)
library(gifski)
library(png)

knitr::opts_chunk$set(
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

mpv_df =
  read_csv("./data/mpv_final.csv")

protest_data =
  read_csv("./data/usa_tidy.csv")
```

<style type="text/css">
h1 {color:slategray;}
</style>

## Motivation

This project is overall motivated by the killing of George Floyd in 2020 and the protests and demonstrations that followed. Police violence and violence against protesters has been a highly talked about issue in 2020 thus far and we were interested in finding and analyzing data related to police violence and the Black Lives Matter protests.

&nbsp;

#### **Motivating Sources**

* "A crisis that began with an image of police violence keeps providing more" from NY Times. [Link](https://www.nytimes.com/2020/06/05/us/police-violence-george-floyd.html)
* "Protests about police brutality are met with wave of police brutality in US" from NY Times. [Link](https://www.theguardian.com/us-news/2020/jun/06/police-violence-protests-us-george-floyd)
* "How George Floyd's death ignited a racial reckoning that shows no sign of slowing down" from CNN. [Link](https://www.cnn.com/2020/08/09/us/george-floyd-protests-different-why/index.html)

&nbsp;

## Questions

The questions for this project are based on the 3 datasets we used that are listed in the next section:

1. What is the spread of police violence over time and space, accounting for basic demographics?
2. What were common characteristics of instances of police violence against individuals, including court rulings of the police involved?
3. What is the geographic spread of Black Lives Matter demonstrations in the US during 2020?
4. How does the spread of Black Lives Matter Protests relate to average income across states and cities in the US?

&nbsp;

## Data
#### *Data Sources*
* Mapping Police Violence in the US -- [Link](https://mappingpoliceviolence.org/)
* ACLED US Crisis Monitor -- [Link](https://acleddata.com/special-projects/us-crisis-monitor/)
* American Community Survey -- [Link](https://www.census.gov/programs-surveys/acs/data.html)

&nbsp;

#### *Variables We Were Interested In*
##### **Police Violence Dataset**
* `age`
* `gender`
* `race`
* `police_dept`: the police department responsible for the individual's death
* `year`
* `city`
* `state`
* `criminal_charges`: whether the police officers involved received criminal charges
* `symptoms_of_mental_illness`: whether the individual killed had symptoms of mental illness


##### **Protest Dataset**
* `month`
* `event_type`: the type of event, ranging from protests to riots
* `sub_event_type`: the sub-type of event, including peaceful protests
* `state`
* `county`
* `fatalities`: number of individuals killed at each event


##### **ACS Dataset**
* `id`
* `county`
* `state`

**Income**
* `total_income`
* `estimate_households`: percent estimate for each county by total household income
* `mean_income`: the mean income in each county
* `median_income`: the median income in each county
* `disparity_value`: mean income - median income in each county
* `income_class`: ranges from "Very Low" to "Very High" based on `median_income` value for each county 

**Age by Sex**
* `age`
* `sex`
* `total`: total estimate for each county by age and sex
* `percent`: percent estimate for each county by age and sex

**Race**
* `race`
* `total`: total estimate for each county for each race category
* `prop`: percent estimate for each county for each race category

&nbsp;

#### *Data Cleaning*
The police violence and protest datasets were both similarly cleaned. The data was first imported into R. The variables were then renamed and selected based on if they were intuitive and if they were needed for this analysis. While the protest data already had a latitude and longitude included, an external source was joined with the police violence dataset so latitudes and longitudes of cities could be included in the dataset.

For the ACS data we looked at Race, Income, and Age by Sex; each category had their own separate dataset. All datasets have a tidy and non-tidy version; tidy datasets were used for visualization and exploratory analyses and the non-tidy datasets were joined with the Police Violence Dataset and Protest Dataset separately in order to conduct further statistical analyses and plotting. However, for both the tidy and non-tidy versions, variable names were shortened for convenience and only a subset of of the original datasets' categories were kept (for example, in all datasets 'margin of error estimates' were removed). Below are the specific data cleaning steps for each dataset:
* **Race:** This dataset excludes data for those who identify as more than one race. Additionally, proportion was calculated for each race category.
* **Age by Sex and Age Only:** The 'Age Only' dataset contains total estimate and percent estimate of each age group and the 'Age by Sex' contains the total and percent estimate for each age group by male or female.
* **Income:** This dataset includes only the total estimates by household income. A variable for income class and disparity value were created.

&nbsp;

## Exploratory Analysis
*ACS Data*

*Police Violence Data*
The exploratory analysis for this dataset was primarily used to visualize the data and help in understanding the shape of the data.
**Age Map with with symptoms of mental illness and whether the officer was charged included**
The following map shows the geographic distribution of individuals killed by police between 2013 and 2020 by age, with information on symptoms of mental illness and whether the officer was charged included.

**Distribution of deaths due to police violence across states**

**Number of individuals killed due to police violence by race**

*Protest Data*

&nbsp;

## Regression Analysis


&nbsp;

## Conclusions


&nbsp;

## Discussion





