---
title: "Final Project Proposal"
output: github_document
---

### Authors

This project will be produced by:

* Rebekah Hughes, UNI: rch2155
* Megan Marziali, UNI: mem2371
* Leighanne Wang, UNI: lw2883
* Jinghan Zhang, UNI:
* Adam Rosenfeld, UNI: 

### Title

Our tentative project title is: **Mapping Police Violence Across the United States: An Analysis of Police Violence and its Results on Correctional Trends**

### Motivation

This project is motivated by the protests occurring in the United States that were spurred by the killing of George Floyd. Along with the violence at protests, this project will examine police violence more broadly and will analyze the results of the police violence on the correctional counts and demographics in the United States. This project is ultimately being completed to assess the instances of excessive use of force by police and to determine whether instances of excessive force are concentrated demographically and geographically.

### Intended Final Products

Our final project will be an HTML website with links to a mapping project. There will be various tabs on the website with different information in each tab and different ways of viewing the data. The landing page of the website will include a brief background on the issue the project is centered around and will give an overview of everything included on the website. There will also be information included on the landing page regarding brief descriptions of how the raw data was manipulated and analyzed to form the final products.

### Anticipated Data Sources

The central data source for the raw data will be the US Crisis Monitor from the Armed Conflict Location and Event Data Project (ACLED). This data gives information on police violence specifically during 2020 following the death of George Floyd. There will also be data regarding police violence, the results of police violence against certain groups of people in the United States, and incarceration trends and their correlation to police violence from New Jersey Projects and Investigations, Fatal Encounters organization, and Prison Policy Initiative organization.

### Planned Analyses/ Visualizations/ Coding Challenges

#### Planned Analyses

We will conduct descriptive analyses of excessive force and other characterizations of protests. We also plan on including an interactive table with geographic specifications detailing protests and characterizations of protests. Based on the counts available, we may be able to explore associations between geographic areas and instances of protests/excessive force (using metro/rural classifications, or other).

**please add to the above here with what you want to do with the other data source and other analyses you want to run. also is this too vague? how detailed is he wanting it? and should we be doing more complex analyses than just descriptives?**

#### Visualizations

This project will include an interactive map with each recorded protest over time, in order to ultimately demonstrate the widespread nature of the protests nationwide.

#### Coding Challenges

We anticipate that small cell counts will be available for some of the outcomes we are interested in, which may limit our ability to run analyses. The data also requires quite a bit of coding. It will also be challenging to create an interactive, time-varying map.

### Planned Timeline

**ok this proposal is due Nov 7, so this is based off a weekly timeline since then and i think this is due.. dec ? also genuinely no gauge on how long some of this will take us, feel free to edit and change dates**

| Week | Action item |
|----------------:|:-----|
| November 7-14 | Data exploration, begin data cleaning, create team plan for appropriate data cleaning steps, complete data cleaning|
| November 14-21 | Make plan for coding the map and for feasible descriptive analyses, run descriptive analyses, being coding map| 
| November 21-28 | Finish coding map, make interactive table to go along with the map |
| November 28-December 5 | Create finished product, troubleshoot to ensure all the links work |



