<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Linear models</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Exploratory Analyses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="analysis_mpv.html">Police Violence</a>
    </li>
    <li>
      <a href="analysis_protests.html">Protests</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Regression Analyses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="regression_mpv.html">Police Violence</a>
    </li>
    <li>
      <a href="regression_protest.html">Protests</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Interactive Maps
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Police Violence</li>
    <li class="dropdown-header">Protests</li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="proj_report.html">Project Report</a>
</li>
<li>
  <a>
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/rebekahhughes97/p8105_final_proj.github.io.git">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Linear models</h1>

</div>


<div id="importing-data" class="section level2">
<h2>Importing Data</h2>
<pre class="r"><code>mpv_df_charges =
  read_csv(&quot;./data/mpv_final.csv&quot;, na = c(&quot;&quot;, &quot;NA&quot;, &quot;Unknown&quot;)) %&gt;% 
  mutate(
    charges = case_when(
      startsWith(criminal_charges, &quot;Charged&quot;) ~ 1,
      startsWith(criminal_charges, &quot;No&quot;) ~ 0),
    resolved = 
           ifelse(startsWith(disposition, &quot;Pending&quot;), 
                  {resolved = 0}, 
                  {resolved = 1}),
    race_rec = case_when(
      race == &quot;Native American&quot; ~ &quot;Other&quot;,
      race == &quot;Pacific Islander&quot; ~ &quot;Other&quot;,
      race == &quot;Black&quot; ~ &quot;Black&quot;,
      race == &quot;Hispanic&quot; ~ &quot;Other&quot;,
      race == &quot;White&quot; ~ &quot;White&quot;,
      race == &quot;Asian&quot; ~ &quot;Other&quot;),
    race_rec = fct_infreq(race_rec),
    age_rec = 
      cut(age, breaks = c(0,20,40,60,100), right = FALSE),
    age_rec = fct_infreq(age_rec),
    MI = case_when(
      symptoms_of_mental_illness == &quot;Yes&quot; ~ 1,
      symptoms_of_mental_illness == &quot;No&quot; ~ 0,
      symptoms_of_mental_illness == &quot;Drug or alcohol use&quot; ~ 0),
    gunshot = case_when(
      cause_of_death == &quot;Asphyxiated&quot; ~ &quot;No&quot;,
      cause_of_death == &quot;Pepper Spray, Physical Restraint&quot; ~ &quot;No&quot;,
      cause_of_death == &quot;Beaten Chemical agent/Pepper spray&quot; ~ &quot;No&quot;,
      cause_of_death == &quot;Gunshot&quot; ~ &quot;Yes&quot;,
      cause_of_death == &quot;Gunshot, Bean Bag Gun&quot; ~ &quot;Yes&quot;,
      cause_of_death == &quot;Gunshot, Beanbag Gun&quot; ~ &quot;Yes&quot;,
      cause_of_death == &quot;Gunshot, Pepper Spray&quot; ~ &quot;Yes&quot;,
      cause_of_death == &quot;Gunshot, Police Dog&quot; ~ &quot;Yes&quot;,
      cause_of_death == &quot;Gunshot, Stabbed&quot; ~ &quot;Yes&quot;,
      cause_of_death == &quot;Gunshot, Taser&quot; ~ &quot;Yes&quot;,
      cause_of_death == &quot;Gunshot, Unspecified Less Lethal Weapon&quot; ~ &quot;Yes&quot;,
      cause_of_death == &quot;Gunshot, Vehicle&quot; ~ &quot;Yes&quot;,
      cause_of_death == &quot;Other&quot; ~ &quot;No&quot;,
      cause_of_death == &quot;Pepper Spray&quot; ~ &quot;No&quot;,
    )) %&gt;% 
  filter(race_rec != &quot;Other&quot;, gender != &quot;Transgender&quot;) %&gt;% 
  select(MI, age_rec, race_rec, charges, gender, gunshot, year, resolved)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   age = col_double(),
##   gender = col_character(),
##   race = col_character(),
##   police_dept = col_character(),
##   disposition = col_character(),
##   year = col_double(),
##   month = col_double(),
##   day = col_double(),
##   city = col_character(),
##   state = col_character(),
##   county = col_character(),
##   cause_of_death = col_character(),
##   criminal_charges = col_character(),
##   symptoms_of_mental_illness = col_character(),
##   lat = col_double(),
##   lng = col_double()
## )</code></pre>
</div>
<div id="model-1-charges" class="section level2">
<h2>Model 1: Charges</h2>
<p>Modeling charges laid as outcome and race as the exposure:</p>
<pre class="r"><code>xtabs(~charges + race_rec, data = mpv_df_charges) %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">White</th>
<th align="right">Black</th>
<th align="right">Other</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0</td>
<td align="right">3689</td>
<td align="right">2074</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="right">57</td>
<td align="right">68</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<pre class="r"><code>glm(charges ~ race_rec, data = mpv_df_charges, family = binomial()) %&gt;% 
  broom::tidy() %&gt;% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %&gt;% 
  select(term, OR, starts_with(&quot;CI&quot;)) %&gt;% 
  mutate(
    term = str_replace(term, &quot;race_rec&quot;, &quot;Race: &quot;)) %&gt;% 
    knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">OR</th>
<th align="right">CI_lower</th>
<th align="right">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.015</td>
<td align="right">0.012</td>
<td align="right">0.02</td>
</tr>
<tr class="even">
<td align="left">Race: Black</td>
<td align="right">2.122</td>
<td align="right">1.486</td>
<td align="right">3.03</td>
</tr>
</tbody>
</table>
<p>Crude analyses show that, in instances where the victim of police violence is Black, the odds of charges being laid is increased by 112% (95% CI: 1.49, 3.03).</p>
<p>The following code chunk explores potential confounders.</p>
<pre class="r"><code>#Year - Not significant, not further explored
glm(charges ~ year, data = mpv_df_charges, family = binomial()) %&gt;% 
  broom::tidy()</code></pre>
<pre><code>## # A tibble: 2 x 5
##   term        estimate std.error statistic p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)  47.0      84.0        0.560   0.575
## 2 year         -0.0252    0.0416    -0.606   0.545</code></pre>
<pre class="r"><code>#Gender - Significant, further explored
glm(charges ~ gender, data = mpv_df_charges, family = binomial()) %&gt;% 
  broom::tidy()</code></pre>
<pre><code>## # A tibble: 2 x 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)    -2.56     0.216    -11.8  3.09e-32
## 2 genderMale     -1.42     0.238     -5.97 2.38e- 9</code></pre>
<pre class="r"><code>glm(charges ~ race_rec + gender, data = mpv_df_charges, family = binomial()) %&gt;% 
  broom::tidy()</code></pre>
<pre><code>## # A tibble: 3 x 5
##   term          estimate std.error statistic  p.value
##   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)     -2.81      0.228    -12.3  7.20e-35
## 2 race_recBlack    0.860     0.185      4.65 3.25e- 6
## 3 genderMale      -1.58      0.243     -6.49 8.35e-11</code></pre>
<pre class="r"><code>#Age - Not significant, not further explored
glm(charges ~ age_rec, data = mpv_df_charges, family = binomial()) %&gt;% 
  broom::tidy()</code></pre>
<pre><code>## # A tibble: 4 x 5
##   term            estimate std.error statistic   p.value
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)       -3.80      0.118   -32.1   4.85e-226
## 2 age_rec[40,60)    -0.163     0.210    -0.777 4.37e-  1
## 3 age_rec[60,100)   -0.150     0.399    -0.376 7.07e-  1
## 4 age_rec[0,20)      0.513     0.329     1.56  1.19e-  1</code></pre>
<p>Adjusted analysis included gender as a confounder.</p>
<pre class="r"><code>glm(charges ~ race_rec + gender, data = mpv_df_charges, family = binomial()) %&gt;% 
  broom::tidy() %&gt;% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %&gt;% 
  select(term, OR, starts_with(&quot;CI&quot;)) %&gt;% 
  mutate(
    term = str_replace(term, &quot;race_rec&quot;, &quot;Race: &quot;)) %&gt;% 
    knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">OR</th>
<th align="right">CI_lower</th>
<th align="right">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.060</td>
<td align="right">0.038</td>
<td align="right">0.094</td>
</tr>
<tr class="even">
<td align="left">Race: Black</td>
<td align="right">2.362</td>
<td align="right">1.645</td>
<td align="right">3.393</td>
</tr>
<tr class="odd">
<td align="left">genderMale</td>
<td align="right">0.207</td>
<td align="right">0.129</td>
<td align="right">0.333</td>
</tr>
</tbody>
</table>
<p>Adjusted analyses show that, in instances where the victim of police violence is Black, the odds of charges being laid is increased by 136% (95% CI: 1.65, 3.39).</p>
<div id="sensitivity-analysis-model-1" class="section level4">
<h4>Sensitivity Analysis: Model 1</h4>
<p>We then opted to conducted a sensitivity analysis, exploring whether a pending investigation was the cause for what seems like a spuriously inflated OR. Therefore, we restricted the sample to only resolved cases.</p>
<pre class="r"><code>mpv_solved = 
  mpv_df_charges %&gt;% 
  filter(resolved == &quot;1&quot;)

glm(charges ~ race_rec + gender, data = mpv_solved, family = binomial()) %&gt;% 
  broom::tidy() %&gt;% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %&gt;% 
  select(term, OR, starts_with(&quot;CI&quot;)) %&gt;% 
  mutate(
    term = str_replace(term, &quot;race_rec&quot;, &quot;Race: &quot;)) %&gt;% 
    knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">OR</th>
<th align="right">CI_lower</th>
<th align="right">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.164</td>
<td align="right">0.103</td>
<td align="right">0.263</td>
</tr>
<tr class="even">
<td align="left">Race: Black</td>
<td align="right">2.282</td>
<td align="right">1.571</td>
<td align="right">3.315</td>
</tr>
<tr class="odd">
<td align="left">genderMale</td>
<td align="right">0.225</td>
<td align="right">0.136</td>
<td align="right">0.373</td>
</tr>
</tbody>
</table>
<p>Adjusted analyses show that, in instances where the victim of police violence is Black, the odds of charges being laid is increased by 128% (95% CI: 1.57, 3.32), adjusting for gender. Restricting to solved cases did not change the association.</p>
</div>
</div>
<div id="model-2-symptoms-of-mental-illness" class="section level2">
<h2>Model 2: Symptoms of Mental Illness</h2>
<p>Modeling symptoms of mental illness as outcome.</p>
<pre class="r"><code>xtabs(~MI + gender, data = mpv_df_charges)</code></pre>
<pre><code>##    gender
## MI  Female Male
##   0    183 3692
##   1     90 1094</code></pre>
<pre class="r"><code>glm(MI ~ gender, data = mpv_df_charges, family = binomial()) %&gt;% 
  broom::tidy() %&gt;% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %&gt;% 
  select(term, OR, starts_with(&quot;CI&quot;)) %&gt;% 
  mutate(
    term = str_replace(term, &quot;gender&quot;, &quot;Gender: &quot;)) %&gt;% 
    knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">OR</th>
<th align="right">CI_lower</th>
<th align="right">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.492</td>
<td align="right">0.382</td>
<td align="right">0.633</td>
</tr>
<tr class="even">
<td align="left">Gender: Male</td>
<td align="right">0.603</td>
<td align="right">0.464</td>
<td align="right">0.782</td>
</tr>
</tbody>
</table>
<p>Gender is significantly associated with MI; males are 40% less likely to exhibit symptoms of mental illness among those killed by police (OR: 0.60; 95% CI: 0.46, 0.78).</p>
<pre class="r"><code>glm(MI ~ race_rec, data = mpv_df_charges, family = binomial()) %&gt;% 
  broom::tidy() %&gt;% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %&gt;% 
  select(term, OR, starts_with(&quot;CI&quot;)) %&gt;% 
  mutate(
    term = str_replace(term, &quot;race_rec&quot;, &quot;Race: &quot;)) %&gt;% 
    knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">OR</th>
<th align="right">CI_lower</th>
<th align="right">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.407</td>
<td align="right">0.377</td>
<td align="right">0.440</td>
</tr>
<tr class="even">
<td align="left">Race: Black</td>
<td align="right">0.398</td>
<td align="right">0.342</td>
<td align="right">0.463</td>
</tr>
</tbody>
</table>
<p>Race is also significantly associated with symptoms of mental illness, in that Black individuals have 0.40 times the odds of reporting symptoms of mental illness (95% CI: 0.34, 0.46).</p>
<div id="sensitivity-analysis-model-2" class="section level4">
<h4>Sensitivity Analysis: Model 2</h4>
<pre class="r"><code>glm(MI ~ gender + race_rec, data = mpv_solved, family = binomial()) %&gt;% 
  broom::tidy() %&gt;% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %&gt;% 
  select(term, OR, starts_with(&quot;CI&quot;)) %&gt;% 
  mutate(
    term = str_replace(term, &quot;race_rec&quot;, &quot;Race: &quot;)) %&gt;% 
    knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">OR</th>
<th align="right">CI_lower</th>
<th align="right">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.467</td>
<td align="right">0.308</td>
<td align="right">0.707</td>
</tr>
<tr class="even">
<td align="left">genderMale</td>
<td align="right">0.934</td>
<td align="right">0.607</td>
<td align="right">1.437</td>
</tr>
<tr class="odd">
<td align="left">Race: Black</td>
<td align="right">0.370</td>
<td align="right">0.287</td>
<td align="right">0.478</td>
</tr>
</tbody>
</table>
<p>After restricting to solved cases, gender was no longer significantly associated with symptoms of mental illness.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
