---
title: "Shiny Dashboard"
output: 
    flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(shiny)
library(plotly)
library(leaflet)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

mpv_data =
  read_csv("./data/mpv_final.csv")

mpv_case = 
  mpv_data %>% 
  mutate(
    charges = case_when(
      startsWith(criminal_charges, "Charged") ~ "Yes",
      startsWith(criminal_charges, "No") ~ "No"),
    MI = case_when(
      symptoms_of_mental_illness == "Yes" ~ "Yes",
      symptoms_of_mental_illness == "No" ~ "No",
      symptoms_of_mental_illness == "Unknown" ~ "NA",
      symptoms_of_mental_illness == "Drug or alcohol use" ~ "No"))

protest_data =
  read_csv("./data/usa_tidy.csv") %>% 
  mutate(
    month_name = 
      recode(month,
            "5" = "May", "6" = "June", "7" = "July", "8" = "August", "9" = "September", "10" = "October")) %>% 
  filter(event_type != "Battles",
         event_type != "Violence against civilians",
         event_type != "Strategic developments")
```

Police Killings 2013-2020
===================================== 

Options {.sidebar}
-----------------------------------------------------------------------

```{r}
charges = 
  mpv_case %>% 
  distinct(charges) %>% 
  pull()

MI = 
  mpv_case %>% 
  distinct(MI) %>% 
  pull()

sliderInput(
  "year_range",
  h3("Year Range"),
  2013, 2020, 
  value = c(2013, 2014),
  sep = "")

selectInput(
  "charges_choice", 
  h3("Charges laid"),
  choices = charges,
  selected = "No"
  )

selectInput(
  "mi_choice", 
  h3("Symptoms of mental illness"),
  choices = MI,
  selected = "No"
  )
```

Column {data-width=800}
-----------------------------------------------------------------------

### Map of Police Killings

```{r}
pal <- colorNumeric(
  palette = "viridis",
  domain = mpv_data$year)

renderLeaflet({
mpv_case %>% 
  drop_na() %>% 
  mutate(
    lab = str_c("City: ", city,
                "<br>Symptoms of Mental Illness: ", symptoms_of_mental_illness,
                "<br>Charges on the Police: ", criminal_charges)) %>%
  filter(
    charges == input[["charges_choice"]],
    MI == input[["mi_choice"]],
    year %in% input[["year_range"]][1]:input[["year_range"]][2]
  ) %>% 
  leaflet() %>% 
  addTiles() %>% 
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addCircleMarkers(
    ~lng, ~lat,
    radius = 0.5,
    popup = ~lab)
})
  
```

Column {data-width=500}
-----------------------------------------------------------------------

### Police Killings by State

```{r}
renderPlotly({
  mpv_case %>% 
    filter(
      charges == input[["charges_choice"]],
      MI == input[["mi_choice"]],
      year %in% input[["year_range"]][1]:input[["year_range"]][2]) %>% 
  count(state) %>% 
  arrange(desc(n)) %>% 
  mutate(
    state = factor(state),
    state = fct_reorder(state, n)
  ) %>% 
    plot_ly(
      y = ~n, x = ~state, color = ~state,
      type = "bar", colors = "viridis") %>% 
    layout(
      yaxis = list(title = "Total Killings"),
      xaxis = list(title = "States", automargin = TRUE, tickangle = 45))
})
```

### Top 10 Cities for Police Killings

```{r}
renderPlotly({
  mpv_case %>% 
    filter(
      charges == input[["charges_choice"]],
      MI == input[["mi_choice"]],
      year %in% input[["year_range"]][1]:input[["year_range"]][2]) %>% 
    count(city) %>% 
    arrange(desc(n)) %>% 
    slice(1:10) %>% 
    plot_ly(
      y = ~n, x = ~city, color = ~city,
      type = "bar", colors = "viridis") %>% 
    layout(
      yaxis = list(title = "Total Killings"),
      xaxis = list(title = "Cities", automargin = TRUE, tickangle = 45))
})
```


2020 Protests
===================================== 

Options {.sidebar}
-----------------------------------------------------------------------

```{r}
month_name = 
  protest_data %>% 
  distinct(month_name) %>% 
  pull()

event_type = 
  protest_data %>% 
  distinct(event_type) %>% 
  pull()

selectInput(
  "month_choice", 
  h3("Month"),
  choices = month_name,
  selected = "May"
  )

sliderInput(
  "date_range",
  h3("Date Range"),
  1, 31, 
  value = c(1, 30),
  sep = "")

selectInput(
  "event_choice", 
  h3("Event Type"),
  choices = event_type,
  selected = "Protests"
  )
```

Column {data-width=800}
-----------------------------------------------------------------------

### Map of Protests and Related Events

```{r}
pal <- colorNumeric(
  palette = "viridis",
  domain = protest_data$month)

renderLeaflet({
protest_data %>% 
  drop_na() %>% 
  mutate(
    lab = str_c("City: ", city,
                "<br>Date: ", day,
                "<br>Fatalities: ", fatalities)) %>%
  filter(
    month_name == input[["month_choice"]],
    day %in% input[["date_range"]][1]:input[["date_range"]][2],
    event_type == input[["event_choice"]]) %>% 
  leaflet() %>% 
  addTiles() %>% 
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addCircleMarkers(
    ~longitude, ~latitude,
    radius = 0.5,
    popup = ~lab)
})
```

### Total Event Type by State

```{r}
renderPlotly({
  protest_data %>% 
    filter(
      month_name == input[["month_choice"]],
      day %in% input[["date_range"]][1]:input[["date_range"]][2],
      event_type == input[["event_choice"]]) %>% 
  count(state) %>% 
  arrange(desc(n)) %>% 
  mutate(
    state = factor(state),
    state = fct_reorder(state, n)
  ) %>% 
    plot_ly(
      y = ~n, x = ~state, color = ~state,
      type = "bar", colors = "viridis") %>% 
    layout(
      margin = list(b = 140),
      yaxis = list(title = "Total Events", range = c(0, 400)),
      xaxis = list(title = "States", automargin = TRUE, tickangle = 45))
})
```


